//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW客戶檢視表
    {
        public string 客戶名稱 { get; set; }
        public int 帳戶數 { get; set; }
        public int 聯絡人數量 { get; set; }
    }
}
